### ISSUE TITLE
Make reflux isomorphic friendly

### ISSUE THREAD

**Issue by spoike** [reflux/refluxjs#144]
Feedback I receive around suggest that reflux needs to be more friendly for isomorphic projects, i.e. same actions and stores can be run both client-side and server-side.

The goal with this issue is how can we achieve this in reflux and still keep a simple API?

Suggestions and PR's are welcome.

**Comment by appsforartists** [comment]
I've posted a [sample project](https://github.com/appsforartists/ambidex-example--bike-index)

**Comment by appsforartists** [comment]
What part [of this](https://github.com/appsforartists/ambidex-example--bike-index/tree/master/application/bike-index/reflux) seemed too complicated?  There's definitely room for improvement, but to my eyes it doesn't seem any more complicated than Reflux itself.

I'm concerned that if you don't run Reflux on the server, you're either losing the benefit of isomorphism or duplicating logic.

**Comment by gpbl** [comment]
yes @appsforartists don't get me wrong, by meeting your same challenges now I understand better the various approaches. That part was clear. Where things get more complex is in the ambidex part: if I understood it right, it is like an abstraction layer over reflux.

When skipping reflux on the server yes, you must duplicate the logic about getting the data. Hence keeping that part simple and reusable by the reflux actions is very important. For now it is a compromise I can accept since it works with the status quo :-)

**Comment by appsforartists** [comment]
Ambidex is a web server for isomorphic React apps.  You would completely replace your Express dependency with it.

I still need to put some docs together, but at a high level, you just make [a settings file](https://github.com/appsforartists/ambidex-example--bike-index/blob/master/application/settings.common.js) that tells it:

 - What is the name of your app? (`NAME` and `SHORT_NAME`)
 - What is the hostname and port you want to serve from? (`HOST` and `PORT`)
 - Do you want live-reload? (`ENABLE_HOT_MODULE_REPLACEMENT`)
 - What folder is your app in? (`BASE`)
  - From that folder, where are your routes located? (`ROUTES`)
  - From that folder, where are your styles located? (`STYLES`)
  - From that folder, where are your Reflux definitions located? (`REFLUX_DEFINITIONS`)
  - From that folder, where is your routerState:actions mapping located? (`REFLUX_ACTIONS_FOR_ROUTER_STATE`)
  - From that folder, what folder should it save your builds in? (`BUNDLES`)

From there, it will do all the *hard* part for you.

I think you're confused because of the `Ambidex.mixinCreators.connectStoresToLocalState` call in the example.  Since Ambidex instantiates (hence owns) your Reflux instances, you have to ask it to return them to you.  You can either use `this.getRefluxStore`/`this.getRefluxAction`, or use the mixin (which serves the same purpose as `Reflux.connect`).

It's definitely a work-in-progress, but you are welcome to use it.  It's the basis for all the work I do for eBay's Mobile Innovations lab.

If you don't want to replace your app server, you could also just import it to steal the Reflux-instantiating code:

 - ["Ambidex/src/callActionsForRouterState.js"](https://github.com/appsforartists/Ambidex/blob/master/src/callActionsForRouterState.js)
 - ["Ambidex/src/mixinCreators/connectStoresToLocalState.jsx"](https://github.com/appsforartists/Ambidex/blob/master/src/mixinCreators/connectStoresToLocalState.jsx)
 - ["Ambidex/src/mixins/RefluxContext.jsx"](https://github.com/appsforartists/Ambidex/blob/master/src/mixins/RefluxContext.jsx)
 - ["Ambidex/src/mixins/Reflux.jsx"](https://github.com/appsforartists/Ambidex/blob/master/src/mixins/Reflux.jsx)

**Comment by influx6** [comment]
Have diligently followed the discussions as best as i could and though having read enough on Isomorphic apps, i can only confess to have only grasp the basics as the usual implementation sides sticks some whats escapes me. But looking at what as been said and worked on by @appsforartists it does seem interesting , a tiny bit complex (not much in code but rather in approach/thinking) and interesting challenging. Like @gpbl, i do agree on simplicity, actually i stick to it but also i see no reason why flux should not run on the server. From the whole discussion, the real key in through is the data and its transition from server-scoped to client-scoped. If FBP has thought me anything while playing with it is,data is freaking flexible and you can get away with anything if you just know how to control it to your taste. 
Rehydrate/Dehydrate is an interesting solution and definately a worthwhile one, now i may be wrong here but the key to isomorphism is the inherent ability for one codebase to work both on server and client to atleast a level and then transition to fully client, allowing us to have basic seo and server-rendered pages while still being fully client-side.

I have not played with reactjs nor reflux to really say enough on it internally works but have been taking my time,studying the written samples and will be looking more into the source. 

But my first Question is:
Data:
What type of data does is exactly contained by the stores and are being hydrated and dyhedrated and how does this data play, if server sided?
Lets imagine for a second that reflux as it is design was purely server-side, how will you handle that data and simply,easily pass it around and render it?

**Comment by appsforartists** [comment]
@influx6, I think of Stores as representing a variable you'd want to track in state.  For instance, if you wrote a component that depended on `this.state.bikes`, then you'd have a `Bikes` store, where `Bikes.state === showBikesComponent.state.bikes`.

It gets a bit more complicated than that when you start talking about serialization because you might have other internal properties to manage.  (For instance, you might have a `CurrentBike` store who emits a BikeModel as its state but also needs to keep track of which `keyName` to look up in the `Bikes` store.)  To serialize the store correctly, you'd need to save/restore both `state` and `keyName`.

**Comment by influx6** [comment]
Sorry for my hast,felt the question might have been abit simplified, indeed the complexity does grow, just as explained.

**Comment by influx6** [comment]
Indeed, the inter-dependencies of stores and their connections with others,I think on the context of serialization, things should be flatten as much as possible,just like a db document that allows embeddement, store serialized data should contain enough information corresponding to the components and keynames associated with them. Just like one would do in a couchdb or mongodb document, that should clear our heads when it comes to dealing with the complexity of dependencies

**Comment by influx6** [comment]
Naturally this will enforce that onces the server grabs the store data,they should be immutable per request, that is values dont change between same component embbedment on the first request from the server, if data changes this propagates along per request,i.e when a new client calls for the application, it gets the latest hot data, these ensures consistency across stores on that request load!

**Comment by influx6** [comment]
But the central issue here is Isomorphism and how do we do it, to simplify our lives!. Lets assume the perfect world on flat dependency i.e as stated when the client request the pages from the server, the serialized data being sent for each store contains the necessary keyname and component reference links/address. How do we do it so simply that allows us to equal render on server and sent that off. My probably naive idea was to create a virtual-dom capable of running both server and client, and allow that to render the first server page load which is sent to client, but these requires in the context of reflux to work on the server. A solution would be to have reflux run on the server, and have that state serialised and sent to the client which then deserializes and continues from there.

**Comment by appsforartists** [comment]
It's not that simple, because things work in a system.

Imagine you have two backend calls going, one to get the details of a bike, and one to get a list of bikes (with fewer details).  You wouldn't want to presume that just because `CurrentBike` had a value, it was ready to serve.  Maybe it was populated by the `/bikes/all/` call, but the `/bike/1045/` call hasn't returned yet.

The right thing to do is to test the value of the store to make sure it passes an acceptability test.  When all the stores are acceptable, render and return.

**Comment by influx6** [comment]
Interesting .....

**Comment by appsforartists** [comment]
One thing to remember with the `callActionsForRouterState` model: it will wait for the results of any parameters it knows how to resolve.  

For instance, consider this URL: `/manufacturers/soma/bikes/juice/` and these routes:

```javascript
    <Route
      path    = "/manufacturers/:manufacturerID/"
      handler = { require('./bike-index/components/ManufacturerDetails.jsx') }
    />
    <Route
      path    = "/manufacturers/:manufacturerID/bikes/:bikeID/"
      handler = { require('./bike-index/components/BikeDetails.jsx') }
    />

    // ------ 

    var refluxActionsForRouterState = [
    {
      "parameterName":  "manufacturerID",
      "actionName":     "getManufacturer",
      "storeName":      "CurrentManufacturer",
    },

    {
      "parameterName":  "bikeID",
      "actionName":     "getBike",
      "storeName":      "CurrentBike",
    },
  ];

```

Even though `BikeDetails` probably doesn't care about the results of `getManufacturer`, it will end up waiting for it before rendering because it matched `manufacturerID`.

You can solve this by prefixing any parameter names you don't care about with a `_`:

```javascript
    <Route
      path    = "/manufacturers/:manufacturerID/"
      handler = { require('./bike-index/components/ManufacturerDetails.jsx') }
    />
    <Route
      path    = "/manufacturers/:_manufacturerID/bikes/:bikeID/"
      handler = { require('./bike-index/components/BikeDetails.jsx') }
    />
```

Now `BikeDetails` will wait for the actions triggered for `bikeID` and `_manufacturerID`.  Since `_manufacturerID` doesn't have an `refluxActionsForRouterState` entry, it will be ignored and we'll only wait for `getBike`.

**Comment by appsforartists** [comment]
I thought about my last comment a bit more, and it's flawed in two ways:

1. This will break your ability to get links to your routes.  If you have something like `getLink({"manufacturerID": "soma", "bikeID": "juice"})`, the `_manufacturerID` will throw it too.

2. You may want to trigger some stores but not others.  For instance, maybe you have a `Manufacturers` store that contains the title you want to put in the address bar, but you also have a store that contains all the bikes that manufacturer produces.  You'd want `getManufacturer` to trigger the one that gives you the name to put in the title bar, but not the one that gets the details of that manufacturer.

This will require more thinking, but `actionsForRouterState` may need refining or replacement.

**Comment by appsforartists** [comment]
I think I need to add an additional filter for `routeName`.  You can add a `routeName` to an `actionsForRouterState` entry and that action will only be triggered if the `routeName` and the `parameterName` match.

**Comment by influx6** [comment]
So to be exact and accurate the actionsForRouterState is very dynamic that based on route will find and link the necessary stores requested?

**Comment by gpbl** [comment]
@influx6 yes, basically the router, server-side, must know about actions and stores necessary to render the route handlers and its subcomponents. 

I solved this skipping an abstraction level and writing a script *for each route*. This script 1) collects the data with a set of API requests, and 2) tells which stores should be hydrated with that data. The goal here is to make the 1st point dynamic enough, so we don't need to duplicate such requests, which are already described in actions and store handlers, but hidden between components and routes.

**Comment by geekyme** [comment]
Would it be possible to seek inspiration from fluxible:

Client - User interactions trigger actions -> actions trigger stores -> stores trigger UI change. 
Server - Page load trigger actions -> actions trigger stores 

Fluxible solved the problem quite effectively by scoping Stores, Actions and Dispatchers to instances with context. However, it involves a great deal of boilerplate and lacks the simplicity and reasonable defaults that Reflux has.

**Comment by przeor** [comment]
Hi Reactors, are there any new examples of Isomorphic Reflux implementations or this is still long term feature??? Thanks in advance for any guidance  :-) as last comment regarding the issue was made few months ago.

**Comment by przeor** [comment]
FYI: after my research I am heading to www.fluxible.io & https://gitter.im/yahoo/fluxible :-)

**Comment by bishtawi** [comment]
I didnt see this listed, but two flux libraries that support isomorphism (and bootstrapping the client store from data serialized from the server) are [flummox](https://github.com/acdlite/flummox/) and [alt](https://github.com/goatslacker/alt).

**Comment by geekyme** [comment]
And fluxible :)

**Comment by bishtawi** [comment]
In case anyone is looking for a complete isomorphic flux implementation, I ended up going with [Marty](https://github.com/martyjs/marty). I found it to be the most feature complete. Their documentation is very mature as well and they have a nontrivial example app. I was able to get my existing website running isomorphically on Marty with little headache in less than a day.

**Comment by leebenson** [comment]
Any update on this?

**Comment by LongLiveCHIEF** [comment]
I'm going to be working on this over the next 3-4 weeks. If anyone wants to help contribute, join the reactiflux slack channel, and keep an eye out for an isomorphic feature branch.

**Comment by lemonCMS** [comment]
Is there any progress on this front?

**Comment by spoike** [comment]
We'll be working on context objects in reflux that will contain dehydrate and hydrate functions to handle this. It will show up in 0.2.x branch soon.

**Comment by andyhite** [comment]
I hate to beat a dead horse, but any update on this?

**Comment by LongLiveCHIEF** [comment]
We know it won't be coming in the 0.2.x branch at this point. There are a ton of bug fixes within the 0.2.x version to fix first.

**Comment by leebenson** [comment]
Reflux is excellent and I don't want to detract its use, but if isomorphic is what you need, check out Yahoo's [Fluxible](http://fluxible.io/)

I'm using it in production. It has per-request contexts, isomorphic function calling via Fetchr, and some decent shortcuts for React components to listen to state changes and effect actions.

Coming from Reflux, some users might initially complain of unnecessary boilerplate, but I've not found that to be the case at all. Once it's set-up, it's trivial to build for.

Really liking it.

**Comment by bbnnt** [comment]
@leebenson what would be the most basic example to date for this implementation ? most starter kits are quite overloaded, they go way further this specific point, so the approach is hard to get

**Comment by leebenson** [comment]
@bbnnt I agree with you - most examples are quite poor, are out of sync with documentation, or just overloaded to the point that it's not always apparent what's going on.

I figured out my flux stack piece by piece. I had intended to write a minimum scaffold via yeoman, but I just don't have the time... and my own implementation now is so far removed from the examples, that copying and pasting blocks of code wouldn't make much sense.

The best place to start with Fluxible specifically is probably http://fluxible.io/guides/bringing-flux-to-the-server.html - the good stuff doesn't start until 90% down, under "Introducing the Fluxible Library". It gives a very succinct example for executing flux on the server, rendering the result through React, throwing the result back to the user, and actions and stores. Although, I recommend you read the full article so you get an idea how you might so that stuff "manually", and then how Fluxible intends to solve it.

If you follow the example, and examine the source thrown back to the browser, you'll get an example for what's going on.

At this point, the best thing to do is study https://github.com/mridgway/flux-example/tree/master/chat to see how the server and client pieces work. The key concept is rehydration. You want to be able to render and execute the flux flow on the server _and_ the client. The way Fluxible allows for this is to send a fluxible "state" object back with the source code that can be parsed on the client, and pick up where the server left off.

The final piece is Fetchr, which is a Fluxible plug-in. Basically, it's an environment-aware plug-in that allows you to call the same code from the client or the server. If called on the server, it will just execute the function locally (since it's defined locally and available to the server.) If called on the client, it will issue an AJAX request to a server end-point that Fetchr sets up, execute it on the client, and then send the result back as JSON. This is really what makes it "isomorphic".

I'd read that same stuff a dozen times before and it made no sense. It was only following the code examples and trying to re-create it piece by piece that it finally occurred to me how each piece fits together.

Sorry I couldn't be more specific.

**Comment by kriscarle** [comment]
In case it helps, I got a form of isomorphic "rehydrate" working using reflux in my fork of the reflux-state-mixin (now called Super-Simple-Flux) adding an option to initialize the store using the props of the connected react component. see https://github.com/openmaphub/Super-Simple-Flux/blob/master/src/connectMixin.js

The basic idea is that the Mixin sits in between the store and Reflux.connect() and provides an opportunity to override getInitialState() before the state is seen by any of the listeners. No more content flashing off and back on again... 

My isomorphic implementation already syncs over props from the server to the client for the top-level component, and that usually is the same data I need for initialState so this works well. Super-Simple-Flux is also a great way to avoid all the boilerplate to keep your component state in sync with the store. It just extends the component's state with the store state. https://github.com/yonatanmn/Super-Simple-Flux.

I also plan to implement a similar feature to restore state from browser local storage for offline/auto-save support.

**Comment by spoike** [comment]
Cool :+1: Should probably add that to the Readme file.
