### ISSUE TITLE
Uncaught Error: Invariant Violation: replaceState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by andreypopp** [reflux/refluxjs#156]
This happens to my app, shouldn't `Reflux.connect` generated mixin check for `this.isMounted()` before setting state? It seems so if Reflux does async event dispatching.

**Comment by chromakode** [comment]
I'm occasionally running into this too in multiple projects. I like @rockymeza's fix -- since EventEmitter3 doesn't handle unsubscribes within an `emit` loop, and the parent-child relationship @bjornua described can cause this to happen, it makes sense to anticipate this exception rather than making React throw. Would a pull request to check `isMounted` before calling `setState` be on the right track?

**Comment by spoike** [comment]
Yes, @chromakode that sounds like a plan.

**Comment by unbracketed** [comment]
I also ran into this behavior. I had a couple of components listening on a store and on an event componentB was getting unmounted within the handler for componentA, yet the event was still passed to componentB.  

As it was a parent/child relationship, I changed to passing props to componentB rather than getting state transitions directly from the store. As @spoike mentions, this is probably the better solution for many cases.

Adding the `isMounted` check seems like a good option. Would it be a good idea for the Store to also log a warning whenever it tries to update an unmounted component?

**Comment by rockymeza** [comment]
I switched to passing through props and I do think it's probably more correct. It would be nice to know what is going on though. It took me a while to find this GitHub issue.

**Comment by drieks** [comment]
Hi, please try my fix from PR #227. This solves the Issue for me.

**Comment by bastiao** [comment]
any plan to merge it?

**Comment by drieks** [comment]
@spoike can you have a look at this change and merge the PR?

**Comment by chromakode** [comment]
As a heads-up: it looks like React 0.14 will no longer throw when `setState` is called on unmounted components (see http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html).

**Comment by spoike** [comment]
Yes. they're deprecating `replaceState` as well. As told in #243

**Comment by devinivy** [comment]
So, `isMounted()` is deprecated and #227 was merged long ago.  This should be resolved, but be on the look-out, and let us know if you come across any edge-cases.
