### ISSUE TITLE
v0.2.12 npm release removes dist directory

### ISSUE THREAD

**Issue by javamonn** [reflux/refluxjs#392]
Hi all,

It appears the latest npm release removes the `dist` directory as well as the compiled `dist/reflux.js` and `dist/reflux.min.js` scripts. Was this intentional? I was manually including these scripts so it was a breaking change for me.

**Comment by javamonn** [comment]
`dist` was added to the .npmignore [here](https://github.com/reflux/refluxjs/commit/ec497c9ced8968405af3a89ec9d906012d03188f)

**Comment by spoike** [comment]
Yes, this is intentional to keep the npm package as small as possible. There are a couple of workarounds:

* Normally when you're using npm packages for the browser environment you'll be transpiling the module with browserify, webpack etc.
* You can install the bower package instead, as it exposes the dist files.

Is this a huge issue for you @javamonn?
