### ISSUE TITLE
Logging interactions between components and actions

### ISSUE THREAD

**Issue by eberhara** [reflux/refluxjs#404]
Hey fellas,

Is it possible to log (info, warn, error) user's interaction through reflux? The idea would be to log any interaction between components and actions.

There is a similar idea on this blog:

https://auth0.com/blog/2015/08/25/logging-and-debugging-in-react-with-flux-replaying-your-users-actions/?utm_content=buffer09781&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

We could have some type of callback function so application could send its logs to a logging server or simply log on console etc...

**Comment by iroy2000** [comment]
I think it is possible,  have you look at "Reflux.StoreMethods"  and "Reflux.ActionMethods"

It is for adding common functionalities into stores or actions.  Since in Reflux the Store can listen to only particular Actions, so in order to have any Actions / Store to have that capabilities, you will want to add those common functions to all Actions / Stores  ( through "Reflux.StoreMethods" or "Reflux.ActionMethods" )
