### ISSUE TITLE
[Question] Clarity on "Aggregate data store" section

### ISSUE THREAD

**Issue by iroy2000** [reflux/refluxjs#405]
Hi all, 

I just want to make sure this is the right assumption or understanding of what the "Aggregate data store" meant.  Since the example doesn't mention much on the overall settings.

Here is my sample code

```js
/**
 *  Example on store data aggregation
 */
var ExampleActions = Reflux.createActions(['greet', 'punch']);

var ExampleStore = Reflux.createStore({
    listenables:[ExampleActions],  // listen to Example Actions
    greet: function(payload) {
        payload = 'Greeting! ' + payload;
        this.trigger(payload);
    }
});

var AnotherStore = Reflux.createStore({
    init: function() {
        this.listenTo(ExampleStore, this.sayHi);  // listen to ExampleStore
    },
    sayHi: function(payload) { 
        payload = 'Hi! ' + payload;
        this.trigger(payload);
    }
});

var ExampleView = React.createClass({
    mixins: [Reflux.connect(AnotherStore,"myState")],  // listen to AnotherStore
    componentWillMount: function() {
        ExampleActions.greet('Roy');   // trigger ExampelActions.greet
    },
    render: function() {
        // ...
    }
});
```

which means that 

setting
-----------
1. ExampleView listen to changes in AnotherStore
2. AnotherStore listen to changes in ExampleStore

flow
------------
1. ExampleView trigger the ExampleActions "greet"
2. ExampleActions will trigger the ExampleStore greet() callback
3. ExampleStore trigger() will trigger the AnotherStore sayHi() callback
4. AnotherStore trigger() will send the data to ExampleView

Question
-------------
1. So is the above example code correct for what the "Aggregate data store" actually mean ?
2. Looks like the "aggregate data store" are mainly designed for data transformation purpose, am I correct ? 

Thanks, just want to clarify what I read from documentation.

**Comment by spoike** [comment]
1. Step 2 is incorrect, the store needs an `onGreet` as a handler for the `greet` action. As this is how listenables are implemented in stores by tacking on `on` as prefix. For the rest you've got the gist of it right. To be more precise `trigger` tells the event emitter inside the action/store to push out whatever arguments you give in `trigger`, which will end up to whatever is listening to it.
2. Yes. I chose term _aggregate_ because that's mainly how I use them, for aggregating/transforming data for components that don't need the whole thing. This is particularly useful in web apps that have multiple mini-SPAs on a page.
