### ISSUE TITLE
support react 0.14

### ISSUE THREAD

**Issue by shipengyan** [reflux/refluxjs#424]
reflux not support react 0.14

![1](https://cloud.githubusercontent.com/assets/1212932/10384491/8fceef20-6e6e-11e5-929b-ede9979494f4.png)

**Comment by allanhortle** [comment]
+1

**Comment by jakoblind** [comment]
+1

**Comment by frost555** [comment]
+1

**Comment by vguzev** [comment]
React v.0.14 was announced two days ago: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html
So, this feature request is critical now. Has anyone tried to fork refluxjs and enable react v.0.14?

**Comment by CrisLi** [comment]
+1
It seems like refluxjs has not been updated for 2 months. Last commit is 2 months ago.

**Comment by STuFF** [comment]
I think the main problem was the "new" path Facebook takes by embracing pure ES6 class. It breaks anything based on mixins, and reflux still has some feature based on mixins. However, I'm using reflux since a few weeks, and all my react code views are pure ES6 classes, I didn't see any blocking point so far.
Still, it's a big move, the doc should be changed, maybe some features are ONLY accessible via mixins etc

**Comment by ce07c3** [comment]
2 months no update basically means it's deserted. Will the maintainer add more maintainers, maybe?

**Comment by dubsar** [comment]
+1
It's a blocking issue.

**Comment by airwin** [comment]
+10086

**Comment by canastro** [comment]
+1

**Comment by srsholmes** [comment]
+1
