### ISSUE TITLE
listenAndPromise is gone in the reflux@0.3.0

### ISSUE THREAD

**Issue by CrisLi** [reflux/refluxjs#427]
First of all, I do like reflux. It is great!

```Uncaught TypeError: LoginAction.login.listenAndPromise is not a function``` I got this error after I upgraded the reflux to version 0.3.0

Then I go through the readme document. The ```listenAndPromise``` method is gone. Why? I do like it. Is there any replacement for this method?

Besides, if there is a upgrade doc, that will be great. Then everyone could know whether should upgrade the reflux.

**Comment by spoike** [comment]
The promise functionality has moved to a seperate package, [reflux-promise](https://github.com/reflux/reflux-promise), since it was causing a lot of issues and it is easier for a user to set it up than to autodetect in Node and browser environments. This is linked from the `CHANGELOG` to the [reflux-core's `CHANGELOG` file](https://github.com/reflux/reflux-core/blob/master/CHANGELOG.md#v030).

**Comment by CrisLi** [comment]
@spoike Thanks a lot

**Comment by spoike** [comment]
The promise functionality has been moved to the separate reflux-promise library.

I'll see if I can add a more clear upgrade note in the README.
