### ISSUE TITLE
str.listen is not support  inES6Store in ie9,10

### ISSUE THREAD

**Issue by juyulin** [reflux/refluxjs#485]
The problem is found in defineReact.js. I find str.isES6Store in undefined in proto.componentWillMount, so 'str.singleton = new singleton;' is not covered during the running time

**Comment by juyulin** [comment]
@maxguzenski

**Comment by timoj** [comment]
It worked for me by just adding `export default <storeclassname>;` At the end of the store class file

**Comment by BryanGrezeszak** [comment]
It is intentional, and documented, that the stores are automatically created during the mounting process. If you're relying on them being made automatically this is the proper time for it to be done.

The pull request for the newest additions also contains documentation as well as methods for creating them yourself before then should you choose for exactly this type of thing.

Unfortunately I don't control merging pull requests. But there is an edge version of reflux which has those features here: https://github.com/BryanGrezeszak/reflux-edge

**Comment by fredabrahamson** [comment]
Was there a solution to this other than using the experimental version of Reflux?

I get a similar error in IE10, `SCRIPT438: Object doesn't support property or method 'listen' `, which is triggered in defineReact(react, reflux), 			 `this.__storeunsubscribes__.push(str.listen(this.setState.bind(this)));`.

I tried using es5-shim and babel-polyfill but the error is still the same.

**Comment by BryanGrezeszak** [comment]
@fredabrahamson 

The new version just allows you to instantiate the store sooner so that you can access it sooner than waiting for the react lifecycle to do it automatically. It's got nothing to do with polyfills/ES5 type stuff.

Whatever's going on with your stuff, you should probably post code that replicates the problem. I've got stuff that runs just fine on IE10.

Sidenote: Reflux ES6 API is just an API that is geared toward ES6 style usage of its API. It's not actually written in ES6 code that needs shims or polyfills or anything. The code you write that implements the API might need it (or might not, depends on your code and your application of it), but Reflux does not.

**Comment by BryanGrezeszak** [comment]
This is an issue with babel.

Babel uses `__proto__` to handle static properties on transpiled classes. That is not good for anything less than IE11.

Read more here: https://babeljs.io/docs/usage/caveats/#internet-explorer

**Comment by coderdave** [comment]
I'm getting this error in reflux 6.4.1 using react-native 0.50.3. What am I doing wrong?

**Comment by codeuniquely** [comment]
Also getting the issue in reflux V6.4.1 and react v16.2.0 - just copied the StateStore example from the online docs...

**Comment by EP36** [comment]
I am getting this issue as well running reflux v6.4.1 and react v16.3.0, same as @codeuniquely

**Comment by EP36** [comment]
@BryanGrezeszak any ideas?
