### ISSUE TITLE
How are keys handled if a component is attached to multiple stores with the same key?

### ISSUE THREAD

**Issue by rkpatel33** [reflux/refluxjs#535]
What will happen if you attache `Store1` and `Store2` to a component using:

```js
this.stores = [Store1, Store2];
```
and both have and `.isLoading` flag? If they get overwritten, is there anyway to preserve the two flags, or do you just have to have them differenly, like `.isStore1Loading` and `.isStore2Loading`?

**Comment by BryanGrezeszak** [comment]
Quite simply: it's not handled. So don't do that.

My basic goal was to keep the automatic mapping extremely simple and predictable. So if you use conflicting names they will do the most predictable thing possible: conflict 😄 

You can either give them unique names, or you can use the more imperative `mapStoreToState` method of mapping state from store to components instead of attaching the store via `this.stores`.

See [this.mapStoreToState](https://github.com/reflux/refluxjs/tree/master/docs/components#manually-mapping-states-with-thismapstoretostate) docs.

**Comment by rkpatel33** [comment]
Ok, that is the assumption I have been working on but thanks for confirming.


_________________________
Rishi Patel | mail@rishinyc.com
