### ISSUE TITLE
Reflux.all() also needs Reflux.waitFor()?

### ISSUE THREAD

**Issue by jessegrosjean** [reflux/refluxjs#55]
First, thanks Reflux, I'm enjoying using it!

I have an aggregate store that depends on two others:

Store1       Store2
      \             /
  AggregateStore

Right now I have AggregateStore listening to the other stores using listenTo. This works, but the aggregate computation can be quite expensive. So if I have some action that touches both Store1 and Store2 the result is that the aggregate computation runs twice. This gets expensive, and makes debugging a bit trickier since the flow passes through the aggregate function multiple times for a single action.

I looked at using Reflux.all to solve the problem. It solves the multiple aggregate computations nicely but introduces a new problem.

Some actions only affect Store1, and in that case I'd still like my AggregateStore to still update immediately with respect to the original action: using the new value from Store1 and the existing value from Store2. But Reflux.all will only fire after both Store1 and Store2 have fired. So in some cases my AggregateStore isn't updated for a long time.

I think Reflux.all() is nice, but I think it also needs a Reflux.waitFor() counterpart that works more like Facebook Flux's waitFor(). Is something like this in the works, or are there suggested workarounds?

**Comment by dtinth** [comment]
I just implemented `Reflux.waitFor()` which is available in [`reflux-waitfor`](https://github.com/dtinth/reflux-waitfor) npm package. (It does not depend on Bacon.js.)

This way, the store will be listening to the action directly, instead of listening to other stores (like original Flux). Now, in your store’s action handler, it can ask Reflux that the action be delivered to some other store (synchronously) first:

```js
  Reflux.listenTo(Store1)
  Reflux.listenTo(Store2)
```

This way, you can also keep your codebase closer to the the original Flux pattern.
