### ISSUE TITLE
Listen methods on actions have no context set

### ISSUE THREAD

**Issue by spoike** [reflux/refluxjs#79]
The `listen` method on actions have lost their `this` context after 0.1.8. Example code:

``` javascript
// Using a bacon stream to listen to an action:
var actionStream = Bacon.fromBinder(myAction.listen);

// will crash on 0.1.8
```

Workaround for now is to bind the action as context, example with lodash:

``` javascript
var actionStream = Bacon.fromBinder(_.bind(myAction.listen, myAction));
```

**Comment by devinivy** [comment]
I thought about this, and I personally don't think this is a bug.  This is just predicable behavior of javascript.  If you want to pass around a method with a specific object as its context, you need to bind that object to the method.  It's the same reason you'd bind `console` to `console.log` if you passed it as a callback.

I suggest the following alternatives,
```js
// Option 1
var actionStream = Bacon.fromBinder(myAction.listen.bind(myAction));

// Option 2
var actionStream = Bacon.fromBinder(function(listenable, cb) {
  return myAction.listen(listenable, cb);
});

// Option 3, experimental ES7 craziness
var actionStream = Bacon.fromBinder(::myAction.listen);
```

**Comment by BryanGrezeszak** [comment]
I agree with @devinivy on this. It's a predictable and normal JS behavior.

I think that this suggestion at one point did make a lot of sense, because React automatically assigned context in its component callbacks. So it would make sense to do it in our stuff to match. Keeping concepts idiomatic between Reflux and React makes a lot of sense.

However, with the now preferred class syntax React no longer does this. Therefore I believe we should follow suit by leaving it as is...because now **not** doing it is idiomatic.

I'll leave it open for a couple days in case someone wants to disagree. Otherwise I'll take the silence as a sign to close.
